### ISSUE TITLE
StatementsFilter chained calls some not returning $this

### ISSUE THREAD

**Issue by srad** [xabbuh/xapi#5]
First of all, thanks for the fantastic work, I really appreciate your library and we are using it currently for an e-learning eval tool at our university.

There is an issue that I noticed with \Xabbuh\XApi\Model\StatementsFilter, which for some filters does not return $this, which makes it a little confusing in which order the filters can be called.

It looks like it was an oversight, i.e. "byRegistration" can't be called before "byActivity" because there was not "this" returned anymore, and that's the case for couple of methods.

I have a couple other issues that I will create issues on and want to know your opinion about.

Thanks!

**Comment by xabbuh** [comment]
Thank you for reporting this issue @srad. I just had a quick look at the source code and this definetely is an issue with our implementation (the docblock is already stating that a `StatementsFilter` instance is returned). I'll publish a patch release soon fixing this issue.

**Comment by xabbuh** [comment]
This will be fixed by php-xapi/model#10.

**Comment by xabbuh** [comment]
I released version `0.3.0` of the `php-xapi/model` package which fixes this issue.
