### ISSUE TITLE
Access context StatementResult

### ISSUE THREAD

**Issue by srad** [xabbuh/xapi#7]
Do you provide access to the context data responded by the xapi server?

**Comment by srad** [comment]
I just tracked down how the response is (de-)serialized with the XMLs and class mappings and so forth.
However, it certainly debatable if such a huge abstraction for a simple JSON-response is not too much, except you are doing much more internal magic with the data.

Is this used for the filters in the clilent of the statementresult? Otherwise it might be more practical to return the json response as pure data, without the serialization (?).

**Comment by xabbuh** [comment]
Currently, neither the model nor the serialzation API do support [xAPI contexts](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#context). This is something I have scheduled for one of the next release. Note however that you should take a look at the different packages (namely `php-xapi/model` and `php-xapi/client`) for future updates as I won't maintain the big monolith repository anymore (creating it was a mistake I made when starting this project).

When it comes to the model and serialisation layer let me explain the reasons that drove me through this architectural decision: While I agree with you that they add some overhead I strongly believe that as a developer it's much more easy to work in a domain that validates itself (more or less). This means that many constraints can be applied automatically to ensure that the user of the API ends up with xAPI statements that are valid (not everything can be ensured at this level though).

One thing that makes the work with the different model classes a bit cumbersome is that you have to take care to wire everything together. To overcome this issue I will integrate a factory that will provide a convient fluid interface to ease the construction of xAPI statements in an upcoming release in the near future.

If you really prefer to build the JSON strings yourself, we can think about a way to work with the client on a much lower level (e.g. directly send and receive JSON strings through HTTP). I am not entirely sure where to put that in the current architecture, but that's definetely something we could solve.

**Comment by srad** [comment]
The main issue when you are typing the response is of course that you have to keep in sync with the spec and in cases like the "context" property you can't type (pseudo-)statically anyways, because the users can add anything in there. So the "context" property would need to return an array anyways which isn't typed (pseudo typed as in PHP...).

**Comment by xabbuh** [comment]
This if basically the same as it is with the document data. So there will be a class implementing the `ArrayAccess` interface.

**Comment by xabbuh** [comment]
This should be resolved by the new `Context` and `ContextActivities` classes of the `php-xapi/model` package. There's no release yet containing these changes, but I plan to release 0.5.0 this weekend. Please let me know if you need anything else.
